data:
    img_dir: images/

alg:
    do_train: True
    train_batch_size: 50
    eval_batch_size: 50
    n_epochs: 1
    n_iter: 1
    in_channels: 3
    latent_dim: 64  # Dimension of the output vector of the encoder
    output_channels: [16, 16, 32, 32]
    kernel_sizes: [5, 5, 3, 3]
    strides: [2, 2, 1, 1]
    paddings: ['same', 'same', 'same', 'same']
#    paddings: [2, 2, 1, 1]
    learning_rate: 1e-4


    vae_config:
        - output_channels: 64
          kernel_size: 3
          stride: 1
          padding: 1
          activation: ReLU

    # The following parameters are specific to the VAE algorithm
