alg:
    bptt_unroll_length: 100
    batch_size: 64
    actor_critic_lr: 1e-3  # (actor-critic loss), 5e-5 for top-down schematic representation with RL-baseline
    base_loss_coeff: 0.5
    entropy_loss_coeff: 1e-3
    rnn_lr: 1e-3
    memory_embed_lr: 3e-3
    rnn_dropout: 0.5